services:
  web:
    build: .
    volumes:
      - .:/app
    image: angelswing-content:latest
    command: bundle exec rails s -u puma -p 3000 -b '0.0.0.0'
    env_file:
      - '.env'
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      # For local development auth method trust is ok
      # But for production, we can set postgres password configuring as following (if we use docker image for database)
      # POSTGRES_USER: $DATABASE_USER
      # POSTGRES_PASSWORD: $DATABASE_PASSWORD
      # POSTGRES_DB: $DATABASE_NAME
      # Set different variable used here in hosting environment 
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  test:
    build:
      context: .
      cache_from:
        - angelswing-content:latest
    image: angelswing-content:latest
    volumes:
      - .:/app
    command: bundle exec rspec
    env_file:
      - '.env.test'
    ports:
      - "3000"
    depends_on:
      - db
    profiles: [ "test" ]
